### ISSUE TITLE
outputs

### ISSUE THREAD

**Issue by ANONOIM123** [FSecureLABS/captcha22#21] opened 2021-09-27 14:40 UTC
python3.7/site-packages/captcha22/lib/crackers/captcha.py", line 208, in solve_captcha
return (json_data['outputs']['output'])
KeyError: 'outputs'

**Comment by ANONOIM123** [comment] 2021-09-27 14:51
Traceback (most recent call last):
  File "/home/administrator/python_main/pythonProject/test.py", line 16, in <module>
    answer = solver.solve_captcha_b64(captcha)
  File "/home/administrator/python_main/pythonProject/venv/lib/python3.7/site-packages/captcha22/lib/crackers/captcha.py", line 251, in solve_captcha_b64
    answer = self.solve_captcha(encoded_string)
  File "/home/administrator/python_main/pythonProject/venv/lib/python3.7/site-packages/captcha22/lib/crackers/captcha.py", line 197, in solve_captcha
    token = self.get_captcha_token(self.captchaID)
  File "/home/administrator/python_main/pythonProject/venv/lib/python3.7/site-packages/captcha22/lib/crackers/captcha.py", line 258, in get_captcha_token
    token = load['captcha']['dataToken']
KeyError: 'captcha'

**Comment by ANONOIM123** [comment] 2021-09-27 14:53
Traceback (most recent call last):
  File "/home/administrator/python_main/pythonProject/test.py", line 16, in <module>
    answer = solver.solve_captcha_b64(captcha)
  File "/home/administrator/python_main/pythonProject/venv/lib/python3.7/site-packages/captcha22/lib/crackers/captcha.py", line 249, in solve_captcha_b64
    answer = self.solve_captcha(encoded_string)
  File "/home/administrator/python_main/pythonProject/venv/lib/python3.7/site-packages/captcha22/lib/crackers/captcha.py", line 208, in solve_captcha
    return (json_data['outputs']['output'])
KeyError: 'outputs'

**Comment by TinusGreen** [comment] 2021-09-27 19:06
Hi Anonoim123, 

I'm going to need more data here to assist.

From what I can read you are trying to use the solver. Have you:

1. Already trained your model?
2. Hosting your model using either captcha22 or tensorflow serving locally?
3. Confirmed that the model is fully operational by using a cURL command to pass a base64 captcha to it?

**Comment by ANONOIM123** [comment] 2021-09-27 21:41
I trained the model and activated it via the client api. I use it locally. cURL did not use, but concerted the image in base64. decode(type:string)

**Comment by TinusGreen** [comment] 2021-09-28 06:16
Hi Anonoim123,

You are going to have to take a slower debugging process here to fix it. Based on the errors you are receiving either your model is not being hosted correctly or you did not supply the cracker script with your specific parameters since you are hosting locally.

My suggestion would be to use the cURL command to first verify that your model is indeed hosting:

```
curl -X POST \
    http://localhost:9001/v1/models/<yourmodelname>:predict \
    -H 'cache-control: no-cache' \
    -H 'content-type: application/json' \
    -d '{
            "signature_name": "serving_default",
            "inputs": 
            {
                "input": { "b64": "/9j/4AAQ==" }
            }
        }'
```
Remember to change the `9001` to the port that you are hosting on and `input` to your base64 encoded captcha. 

If this works it means your model is hosted correctly. Then you will have to either review the parameters of the example cracker scripts using `captcha22 client cracker -h` or, copy and create your own cracker based on this example. We only provide cracker examples that interface with the captcha22 API, so you will have to make some modifications for your specific use case.

**Comment by ANONOIM123** [comment] 2021-09-28 15:47
CURL send 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

**Comment by ANONOIM123** [comment] 2021-09-28 15:50
INFO:werkzeug:192.168.1.64 - - [28/Sep/2021 21:45:37] "POST /v1/models/cap22:predict HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [28/Sep/2021 21:46:10] "POST /v1/models/cap22:predict HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [28/Sep/2021 21:47:47] "POST /v1/models/cap22:predict HTTP/1.1" 405 -

**Comment by TinusGreen** [comment] 2021-09-28 18:48
Hi Anonoim123,

I'm closing this ticket as you are not providing sufficient data for me to debug your issue and from what I can see, this is not an issue with captcha22.

You stated that you are hosting the tensorflow model locally, however the output you have provided shows that you are trying to make the cURL request to the captcha22 API, not directly to the tensorflow serving model. 

You have two options for using a trained model:

*Option 1:*

You can use captcha22's server and API.
1. Start the captcha22 server - `captcha22 server engine` - Make sure your parameters are correct
2. Start the captcha22 API server - `captcha22 server api` - Make sure your parameters are correct
3. Run the captcha22 API client - `captcha22 client api` - Ensure you provide the path to where your API is being hosted
4. Using the client, select option `3`, list your captcha according to its ID and select the option to enable the model hosting
5. You can confirm that the model is being hosted by running `ps aux | grep "server"`. If the model is not working, you will need to ensure that you have installed the tensorflow model serving dependencies and if the issue persists, either try to run the model locally or log an issue request with tensorflow.
6. Once the model is running, you will be able to once again run option `3` on the client and upload a captcha sample for cracking. Or, you can modify the sample script to use that for uploading captchas to be cracked. Or, you can directly send you captchas for cracking to the hosted model, but make sure you know what the required ports are for the hosted model using the `ps aux` command.

*Option 2:*

You can export the model from the captcha22 server and host it locally using tensorflow model serving.

1. Export the model either through the API interface (option `3`) or by simply navigating to the `Busy` or `Models` directory and pulling the zipped model.
2. Use the tensorflow model serving command to host the model. Example `tensorflow_model_server --port=9000 --rest_api_port=9001 --model_name=yourmodelname --model_base_path=./exported-model`
3. Once hosted, you can directly interface with this model by using cURL for example, same as the example provided above.


If you require more assistance, please provide detailed notes on what you are executing and the output received at each step. Otherwise I will not be able to provide additional assistance.

**Closed as completed by TinusGreen** 2021-09-28 18:48 UTC
